### ISSUE TITLE
SKRIVEFEIL!

### ISSUE THREAD

**Issue by antring** [antring/inventory-ks#11]
Skrivefeil overalt. 
Så om du finner noen så noter de her så jeg får fikset de...

**Comment by antring** [comment]
Media på hovedmenyen.

**Comment by antring** [comment]
Mange feil på categorie..... på  categorie.php

**Comment by spot88** [comment]
* admin.php  - "Highest saleing products"
* product.php - "Saleing Price"

**Comment by antring** [comment]
Oversettelsen har fikset mesteparten.
