### ISSUE TITLE
Småfix samling #1

### ISSUE THREAD

**Issue by antring** [antring/inventory-ks#30]
* Salg må gå ut fra ks-lager
* Mulighet for «transfere» mellom lager? Egen knapp, med pop up for antall?
* Dashboard  link til oppsummering av lagerstatus per produkt event. kall «sales report» for Report og lag en lager status rapport
* «latest sales» sorter på dato

**Comment by antring** [comment]
Latest sales er allerede sortert på dato? @spot88
Mulighet for å utdype hva som skulle fikses på den?

**Comment by antring** [comment]
Lagerstatusrapport, hva burde den inneholde? @spot88

**Comment by spot88** [comment]
@antring 
Latest sales se #40
Lagerstatusrapport: Produkt, hovedlager, ks-lager, totalsalg(ut av lager) 

Kommer ikke på noe mer, kanskje du har noen ideer.
