### ISSUE TITLE
Kommentar på produktsalg

### ISSUE THREAD

**Issue by Judoflip** [antring/inventory-ks#51]
Man kan skrive inn en veldig lang kommentar, som forskyver siden.

**Comment by antring** [comment]
Skjer kun når det er ord som er usaklig store. På lange kommentarer fungerer det som intended
![skjermbilde](https://cloud.githubusercontent.com/assets/4933033/11501104/fbdf4344-9831-11e5-8264-44cfe3a23b0c.PNG)
