### ISSUE TITLE
Dekoder

### ISSUE THREAD

**Issue by Judoflip** [antring/inventory-ks#53]
Ekstra dekoder og hoveddekoder er samme dekoder (på lager) og må ha samme lagerstatus.

**Comment by spot88** [comment]
* Hoveddekoder har fått nytt navn, Dekoder med PVR. Her må trekkes fra en dekoder og pvr fra lagerstatus.

**Comment by antring** [comment]
Denne krever databaseoppdatering så blir løst på db v2
