### ISSUE TITLE
negativ verdi på antall

### ISSUE THREAD

**Issue by Judoflip** [antring/inventory-ks#56]
Kundebehandler kan øke lagerstatus (ks-lager) ved å legge inn negativ verdi på antall.

**Comment by spot88** [comment]
* Kan fortsatt legge til negativ verdi på antall, men den øker ikke lagerstatus lenger.

**Comment by antring** [comment]
Vil ikke kunne forandre noe i databasen selv om brukeren prøver å skrive negative tall.
