### ISSUE TITLE
enhancements - sales.php

### ISSUE THREAD

**Issue by spot88** [antring/inventory-ks#7]
* Bør kanskje bare vise egne salg.
   * Utenom admin.
* Fjerne $ tegn.

**Comment by spot88** [comment]
Fjerne diverse $ tegn.

**Comment by antring** [comment]
* Legge til attributt på sales som knytter bruker til 
* Legge til i sql-spørringen for ks og lev at det kun skal vises egne salg.

**Comment by spot88** [comment]
* Denne siden viser egne salg, og du har mulighet for endre dine egne salg. F.eks. kunden ringer tilbake og sier han trenger 2.stk dekodere ikke 1.

**Comment by antring** [comment]
Endring av quantity er allerede i prosjektet. Så trenger ikke gjøre noe med den.
