### ISSUE TITLE
enhancements - add_sale.php

### ISSUE THREAD

**Issue by spot88** [antring/inventory-ks#8]
* Dropboks for produkter. 
* Ikke mulighet for å endre pris og total. 
* Legge til et kommentarfelt, med mulighet for Navn,Prosjekt,Kundenr. (3 siste er lav prio). 
* Knyttes mot bruker som er logget inn. 
* Legge til en knapp som viser at kunden har fått det gratis. 
   * Price settes da til 0, men total må fortsatt være.

**Comment by antring** [comment]
Må oppdatere database med attributt for kundenr og kommentar. 
Kundenr blir required info på salg. Kommentar

**Comment by antring** [comment]
Ikke lagt til knapp for å sette pris til gratis, ellers alt gjort.

**Comment by spot88** [comment]
Forslag til Layout: 
![forslag](https://cloud.githubusercontent.com/assets/10884072/11337108/b01b0b02-91ea-11e5-8915-4d9a59bb1621.jpg)

**Comment by spot88** [comment]
* Hvordan har vi tenkt på det med f.eks. en ny kunde, som skal ha en Hoveddekoder ikke en ekstra dekoder. - Skulle ha lagt til en "knapp" for 'Ny kunde'.
