### ISSUE TITLE
enhancements - admin.php

### ISSUE THREAD

**Issue by spot88** [antring/inventory-ks#9]
* Lage til ei fane ala, Users/categories som lister opp status på Hovedlager og KS-lager.
    * Fjerne Products/Categories? Hvis det blir for mye med 5stk på toppen der. 
* Lastest sales bør inneholde brukernavn. 
* "Highest saleing product" bør inneholde "Totale Sale" (lav prio).
* Fjerne $ tegnet.

**Comment by antring** [comment]
Sjekke ut admin v2 før noe gjøres her.

**Comment by spot88** [comment]
auth_v2.php
